version: "3.9"

services:
  app:
    build: .
    container_name: ninja-chess-server
    restart: unless-stopped
    ports:
      - "8200:8200"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    env_file:
      - .env
